# Generated by Django 5.1 on 2024-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='ОПИСАНИЕ ОРГАНИЗАЦИИ')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='НОвости на сегодня')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('data_time', models.DateField(default='2024-09-09')),
            ],
        ),
    ]
