# Generated by Django 5.1 on 2024-09-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_about_alter_news_data_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
