# Generated by Django 5.1.1 on 2024-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_delete_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AddField(
            model_name='info',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='info_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='data_time',
            field=models.DateField(default='2024-10-08'),
        ),
    ]
