# Generated by Django 5.1.1 on 2024-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_news_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data_time',
            field=models.DateField(default='2024-12-06'),
        ),
    ]
